package szabados.alpar.exercises.leetCodeSolutions;

import java.util.stream.IntStream;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class _389_FindTheDifference {
    public char findTheDifference(String s, String t) throws IllegalArgumentException {
        int[] chars = new int[255];

        t.chars().forEach(c -> chars[c] += 1);
        s.chars().forEach(c -> chars[c] -= 1);

        return (char) IntStream.range(0, chars.length).filter(i -> chars[i] != 0).findFirst().getAsInt();
    }
}
